const oneTimePaymentMock = {
  id: '72737501101206965',
  accountNumber: '72737501101206965',
  pin: '7603',
  accountPin: {
    accountUuid: '90459005-40a8-1a06-a62b-0004ac1be08b',
    pinNumber: '36900',
    created: {
      userId: null,
      source: 'CDB',
      dateTime: '2022-01-14T00:43:58-05:00',
    },
    updated: {
      userId: null,
      source: 'CDB',
      dateTime: '2022-01-14T01:43:12-05:00',
    },
  },
  dataRegion: 'FT',
  firstName: 'MARIANNE',
  lastName: 'BALDA',
  accountType: 'Residential',
  paperless: true,
  paperBillFee: '2.99',
  bill: {
    balanceBeforeCurrentCharges: { amount: 191.54 },
    lastStatementBalance: { amount: 191.54, date: '2022-10-10' },
    paymentSinceLastStatement: { amount: 0, date: '' },
    paymentReceivedSinceLastStatement: { amount: 0 },
    creditsOrAdjustments: { amount: 0, status: 'applied' },
    pendingPayment: { amount: 0, date: '', isAutoPayMode: true },
    pendingPayments: { amount: 0 },
    scheduledPayments: { amount: 0 },
    pastDueBalance: { amount: 0, date: '2022-10-10' },
    currentBalance: { amount: 191.54, dueDate: '2022-11-03' },
    manageBillData: {
      balanceBeforeCurrentCharges: 0,
      currentCharges: 191.54,
      amountOfLastBill: 192.14,
      paymentReceivedThruText: 'Payments Received ',
      lastBillDate: '2022-10-04',
      paymentReceivedThruAmount: -192.14,
    },
    isPastDue: false,
    consolidatedBalance: {
      pendingEBPPPaymentsNotInDPI: { amount: '0' },
      pendingUnpostedPayments: { amount: '0' },
      postedUnbilledBelowTheLineAdjustments: { amount: '0' },
      currentBalanceInDPI: { amount: '191.54' },
      consolidatedBalanceDue: { amount: '191.54' },
    },
  },
  billingAddress: {
    street: ['9101 CALLE ALTA'],
    city: 'NEW PRT RICHY',
    state: 'FL',
    zip: '346555243',
  },
  billingContactEmail: 'MIMI6140@VERIZON.NET',
  primaryContact: 'mimi6140@aol.com',
  serviceRefreshEligible: true,
  preferredLanguageCode: 'ENG',
  obpStatus: true,
  constraints: {
    payments: {
      minimumAmount: 1,
      maximumAmount: 3000,
      latestScheduledPaymentDate: '2022-11-27',
    },
    blocking: {
      isBlockedForACH: false,
      isBlockedForCard: false,
      isBlockedForPaymentVelocity: false,
    },
  },
  autopayType: 'fiserv',
  ecommerceEnabled: false,
}

export const mockPaymentMethodsData = {
  profile: {
    email: 'ftrqat03+3@gmail.com',
    address: {
      addressLine1: '',
      addressLine2: '',
      city: '',
      state: '',
      zipCode: '',
    },
  },
  paymentMethods: [
    {
      id: 'FF3D5736-F842-43F4-9B74-D952C385E41C',
      status: 'VALIDATED',
      type: 'Checking',
      default: true,
      nickName: 'CHECKING ending in 2024',
      subtype: 'CHECKING',
      accountHolderName: {
        firstName: 'Johnny',
        lastName: 'Scizz',
      },
      accountNumberEndsWith: '2024',
      systemOfOrigin: 'DST',
      description: 'CHECKING ending in 2024',
      updateable: true,
      deleteable: true,
      class: 'PERSONAL',
    },
    {
      id: 'A764F0BD-6C68-409C-B563-B6137D3CC8F0',
      status: 'Expired',
      type: 'Card',
      default: false,
      nickName: 'Commercial Credit Card',
      subtype: 'VISA',
      accountNumberEndsWith: '1405',
      systemOfOrigin: 'DST',
      description: 'VISA ending in 1405',
      updateable: true,
      deleteable: true,
      class: 'BUSINESS',
    },
    {
      id: '3F83F792-0377-4B61-9578-93827DB69010',
      status: 'REGISTERED',
      type: 'Card',
      default: false,
      nickName: 'MASTERCARD ending in 9456',
      subtype: 'MASTERCARD',
      accountNumberEndsWith: '9456',
      systemOfOrigin: 'DST',
      description: 'MASTERCARD ending in 9456',
      updateable: true,
      deleteable: true,
      class: 'BUSINESS',
    },
    {
      id: '5BD6D82F-54CA-4355-945E-22FD254FDB61',
      status: 'VALIDATED',
      type: 'Card',
      default: false,
      nickName: 'MASTERCARD ending in 8306',
      subtype: 'MASTERCARD',
      accountNumberEndsWith: '8306',
      systemOfOrigin: 'DST',
      description: 'MASTERCARD ending in 8306',
      updateable: true,
      deleteable: true,
      class: 'PERSONAL',
    },
  ],
}

export const paymentConfirmation = {
  email: 'ck75253+5@gmail.com',
  date: '2022-11-03',
  fundingType: 'ONE_TIME_ACH',
  addToWallet: true,
  token: '880386C0-E3D4-4330-9620-EBC9FDACCAA2',
  amount: '',
  customerType: 'RESIDENTIAL',
  customerName: 'CETCTESTPASSLOW-C',
}

export default oneTimePaymentMock
