# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  - none

pool:
  name: DIGITAL26
  demands: npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: Install NPM Packages
    inputs:
      command: 'install'

  - task: Npm@1
    displayName: Build the Application
    inputs:
      command: 'custom'
      customcommand: 'run build'

  - task: Npm@1
    displayName: Run Unit Tests
    inputs:
      command: 'custom'
      customcommand: 'run test:ci'
