declare const styles: {
  readonly hero: string
  readonly heroBkgd: string
  readonly tvHero: string
  readonly bkgGravity: string
  readonly bkgBlack: string
  readonly bkgWhite: string
  readonly bkgGravity5: string
  readonly heroContainer: string
  readonly subHeader: string
  readonly buttonsContainer: string
  readonly picture: string
  readonly h1Hero: string
  readonly h1LogoTitle: string
  readonly primaryButton: string
  readonly secondaryButton: string
  readonly heroLeft: string
  readonly h1MainTitle: string
  readonly legalText: string
  readonly stripes: string
  readonly winStripes: string
  readonly stripesRight: string
  readonly stripe: string
  readonly primaryStripe: string
  readonly tertiaryStripe: string
  readonly wrappedHero: string
  readonly removeStripes: string
  readonly toolTip: string
  readonly subHeaderInline: string
  readonly subHeaderWithOutToolTip: string
}
export = styles
