declare const styles: {
  readonly header: string
  readonly headerNav: string
  readonly hideUtilityNavMobile: string
  readonly hideUtilityNavTablet: string
  readonly hideMainNavMobile: string
  readonly hideMainNavTablet: string
  readonly headerNavContainer: string
  readonly headerHamburgerButton: string
  readonly headerHamburgerButtonContainer: string
  readonly hideHamburgerButton: string
  readonly headerLogo: string
  readonly signInMobile: string
  readonly navContainer: string
  readonly navSecondary: string
  readonly navSecondaryAnchor: string
  readonly navSecondaryTitle: string
  readonly accordionContainer: string
  readonly toggleButton: string
  readonly toggleButtonOpen: string
  readonly toggleButtonClose: string
  readonly shouldAnimate: string
  readonly toggleButtonLineOne: string
  readonly toggleButtonLineTwo: string
  readonly toggleButtonLineThree: string
  readonly toggleNavOpen: string
  readonly toggleNavClose: string
  readonly hideLogoTablet: string
  readonly hideLogoMobile: string
  readonly loggedInUserNameWrapper: string
  readonly profileDropdown: string
  readonly profileCloseIcon: string
  readonly mobileUtilityNav: string
  readonly headerBanner: string
  readonly bannerText: string
  readonly hideSearch: string
  readonly showSearch: string
  readonly headerMobileLogo: string
  readonly profileDropDownlist: string
  readonly profileDropdownOpen: string
  readonly profileTitle: string
  readonly profileTitleDropDownlist: string
  readonly profileDropdownContainer: string
  readonly buyLinkContainer: string
  readonly hide: string
  readonly loggedInText: string
  readonly signInTextAccountDashboard: string
  readonly profileTitleAccountDashboard: string
  readonly accountDashboardMobileCartContainer: string
  readonly accordionContainerAccountDashboardMobile: string
  readonly profileDropdownItemAccountDashboard: string
}
export = styles
