export { default as ActivationHero } from './activate/ActivationHero'
export { default as ErrorHero } from './activate/ErrorHero'
export { default as OfferHero } from './activate/OfferHero'
export { default as YoutubeTvFAQ } from './shared/Faq'
// export { default as Testimonials } from './activate/Testimonials'
export { default as GetStarted } from './activate/GetStarted'
export { default as BetterWithFrontier } from './activate/BetterWithFrontier'
export { default as ConfirmationHero } from './confirmation/ConfirmationHero'
