# logic to delete workspaces and remove cloud resources created by it
name: Terraform Maintenance
on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:

jobs:
  cleanupTF:
    name: "Cleanup Terraform workspaces"
    runs-on: ubuntu-latest
    env:
      organization: "frontier-devops"
      tf_token: ${{ secrets.TF_API_CALLS }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Maintenance for Terraform Workspaces
        uses: ./.github/actions/CleanupTF