name: "HealthCheck"
description: "Endpoint HealthCheck"

inputs:
  url:
    description: "Endpoint url"
    required: true
  status_code:
    description: "Terraform variable to search for"
    required: false
    default: 200

runs:
  using: "composite"
  steps:
  - name: "HealthCheck"
    id: hc
    shell: pwsh
    run: |
      try {
        [String]$uri = "${{ inputs.url }}"
        [Int]$timeout = 10
        [Int]$nAttempts = 12 
        [Int]$StatusCode = "${{ inputs.status_code }}"

        Write-Host "Healthcheck. Valid response code is '$StatusCode'. Endpoint is '$uri'"

        while ($nAttempts -gt 0) {
            try {
                $response = Invoke-WebRequest -Uri $uri
            } catch {
                # Need silently continue here and retry
                #$msg = "Unexpected response received. Status Code : '$($_.Exception.Response.StatusCode.Value__)'. Description : '$($_.Exception.Response.StatusDescription)'."
                #Throw "$msg Details:`r`n`t$($_)"
                Write-Host "Retrying healthcheck due to the unexpected response received. Status Code : '$($_.Exception.Response.StatusCode.Value__)'. Description : '$($_.Exception.Response.StatusDescription)'."
            }

            if ($response.statuscode -eq $StatusCode) {
                Write-Host "Healthcheck call was successful"
                Break
            } else {
                if ($nAttempts -gt 1) {
                    Write-Host "Retrying healthcheck due to the unexpected response statuscode '$($response.statuscode)' received"
                    Start-Sleep -s $timeout
                    $nAttempts--
                    Continue
                }
                $msg = "Unexpected response code '$($response.statuscode)' received."
                Throw $msg
            }
        }

        Write-Host "Action execution completed successfully"
        Exit 0
      } catch {
        Write-Host "[ERR]: $($_.Exception)"
        Write-Host "Action execution failed"
        Exit 1
      }   