export const stateConstant = {
  RESET_PASSWORD_EMAIL_FORM: 'RESET_PASSWORD_EMAIL_FORM',
  RESET_PASSWORD_FORM: 'RESET_PASSWORD_FORM',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_FORM_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FORM_FAIL',
}
