name: "Remove Terraform Workspace"
description: "Remove Terraform Workspace"

inputs:
  tf_token:
    description: "Terraform token"
    required: true
  tf_wsp_name:
    description: "Terraform Workspace name"
    required: true

runs:
  using: "composite"
  steps:
  - name: "Remove Terraform Workspace"
    id: delWsp
    shell: pwsh
    run: |
      try {
        [String]$token = "${{ inputs.tf_token }}"
        [String]$wspName = "${{ inputs.tf_wsp_name }}"
        [String]$uri = "https://app.terraform.io/api/v2/organizations/${{env.organization}}/workspaces/$wspName"

        $headers = @{
          'Authorization' = "Bearer ${{ inputs.tf_token }}"
          'Content-Type' = 'application/vnd.api+json'
        } 

        Write-Host "Remove Terraform Workspace '$wspName'"
        try {
          $response = Invoke-WebRequest -Uri $uri -Method DELETE -Headers $headers
        } catch {
          $msg = "Unexpected response received. Status Code : '$($_.Exception.Response.StatusCode.Value__)'. Description : '$($_.Exception.Response.StatusDescription)'."
          Throw "$msg Details:`r`n`t$($_)"
        }

        if ($response.statuscode -eq '204') {   
          Write-Host "Workspace with the name '$wspName' was successfully deleted from Terraform"
        } else {
          $msg = "Unexpected response code '$($response.statuscode)' received while removing Terraform workspace."
          Throw $msg  
        }
        
        Write-Host "Action execution completed successfully"
        Exit 0
      } catch {
        Write-Host "[ERR]: $($_.Exception)"
        Write-Host "Action execution failed"
        Exit 1
      }